name: Use Repository Secrets

on:
  workflow_dispatch:
 # push:
 #   branches:
  #    - main  # Trigger workflow on push to main branch

env:
  app_password: ${{ secrets.APP_PASSWORD }}  # Access secret

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python environment
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Python script
      
      run: |
        python ConnectMySQL.py
